on: [push]

jobs:
  test1:
    runs-on: ubuntu-latest
    name: test

    strategy:
      matrix:
        check:
          - '{"dog" : "dog", "cat": "cat"}'
          - '{ "(dog|cat)" : "animal"   }'
          - '{ "/(dog|cat)/im" : "animal", "/(volvo|BMW)/im" : "Car"}'
          - '{ "/(volvo|BMW)/im" : "Car", "/(dog|cat)/im" : "animal"}'
    steps:
      - uses: actions/checkout@v2
      - name: Manual Action Test
        id: test_action
        uses: ./
        with:
          input: "this string has animals: cat\n and cars: Volvo "
          json_match: ${{ matrix.check }}
          success_if_no_match: false
      - run: |
          echo "${{ steps.test_action.outputs.result }}"

  test2:
    runs-on: ubuntu-latest
    name: test

    strategy:
      matrix:
        check:
          - '{
          "/animal[^\\w\\n\\r]*dog\\b/i" : "dog", 
          "/animal[^\\w\\n\\r]*cat\\b/i": "cat"
          }'
    steps:
      - uses: actions/checkout@v2
      - name: Manual Action Test
        id: test_action
        uses: ./
        with:
          input: "animal:   CAT"
          json_match: ${{ matrix.check }}
          success_if_no_match: False
      - run: |
          echo "${{ steps.test_action.outputs.result }}"
